"""One-click SFX presets. id: snake_case, label: Japanese, prompt: English (for text-to-audio)."""

PRESETS = [
    # 自然
    {"id": "rain", "label": "雨", "category": "自然",
     "prompt": "heavy rain falling on a tin roof with distant thunder", "duration": 6.0},
    {"id": "thunder", "label": "雷", "category": "自然",
     "prompt": "a loud thunder clap followed by a deep rumbling echo", "duration": 4.0},
    {"id": "wind", "label": "風", "category": "自然",
     "prompt": "strong wind gusting through trees and rattling leaves", "duration": 6.0},
    {"id": "river", "label": "川", "category": "自然",
     "prompt": "a gently flowing river with bubbling water over rocks", "duration": 6.0},
    {"id": "waves", "label": "波", "category": "自然",
     "prompt": "ocean waves crashing rhythmically on a sandy beach", "duration": 6.0},
    {"id": "campfire", "label": "焚き火", "category": "自然",
     "prompt": "a crackling campfire with popping wood embers", "duration": 6.0},

    # 動物
    {"id": "dog_bark", "label": "犬", "category": "動物",
     "prompt": "a medium-sized dog barking sharply three times", "duration": 3.0},
    {"id": "cat_meow", "label": "猫", "category": "動物",
     "prompt": "a cat meowing softly twice in a quiet room", "duration": 3.0},
    {"id": "birds", "label": "小鳥", "category": "動物",
     "prompt": "small birds chirping cheerfully in a forest morning", "duration": 5.0},
    {"id": "crow", "label": "カラス", "category": "動物",
     "prompt": "a crow cawing loudly outdoors", "duration": 3.0},
    {"id": "cicada", "label": "セミ", "category": "動物",
     "prompt": "loud cicadas buzzing on a hot summer day", "duration": 6.0},

    # 生活
    {"id": "door_open", "label": "ドア開", "category": "生活",
     "prompt": "a wooden door creaking open slowly", "duration": 2.5},
    {"id": "door_close", "label": "ドア閉", "category": "生活",
     "prompt": "a wooden door closing shut with a solid thud", "duration": 2.0},
    {"id": "knock", "label": "ノック", "category": "生活",
     "prompt": "someone knocking on a wooden door three times", "duration": 2.5},
    {"id": "footsteps", "label": "足音", "category": "生活",
     "prompt": "footsteps walking on a hardwood floor", "duration": 4.0},
    {"id": "glass_break", "label": "ガラス割れ", "category": "生活",
     "prompt": "a glass pane shattering into pieces on a hard floor", "duration": 2.5},
    {"id": "phone_ring", "label": "電話", "category": "生活",
     "prompt": "an old telephone ringing repeatedly", "duration": 4.0},
    {"id": "clock_tick", "label": "時計", "category": "生活",
     "prompt": "a mechanical clock ticking steadily in a quiet room", "duration": 5.0},
    {"id": "doorbell", "label": "チャイム", "category": "生活",
     "prompt": "a two-tone electronic doorbell chime", "duration": 2.0},
    {"id": "keyboard", "label": "キーボード", "category": "生活",
     "prompt": "fast mechanical keyboard typing clicks", "duration": 4.0},
    {"id": "camera", "label": "カメラ", "category": "生活",
     "prompt": "a camera shutter click and film advance sound", "duration": 2.0},

    # 人
    {"id": "applause", "label": "拍手", "category": "人",
     "prompt": "a small crowd applauding enthusiastically", "duration": 4.0},
    {"id": "cheer", "label": "歓声", "category": "人",
     "prompt": "a crowd cheering and shouting with excitement", "duration": 4.0},
    {"id": "laugh", "label": "笑い声", "category": "人",
     "prompt": "a group of people laughing together", "duration": 3.0},
    {"id": "heartbeat", "label": "心拍", "category": "人",
     "prompt": "a slow steady human heartbeat, deep low thud", "duration": 5.0},

    # 機械・乗り物
    {"id": "car_engine", "label": "車エンジン", "category": "機械・乗り物",
     "prompt": "a car engine starting up and idling", "duration": 5.0},
    {"id": "car_horn", "label": "クラクション", "category": "機械・乗り物",
     "prompt": "a car horn honking twice sharply", "duration": 2.0},
    {"id": "train", "label": "電車", "category": "機械・乗り物",
     "prompt": "a train rattling along tracks with a distant horn", "duration": 6.0},
    {"id": "siren", "label": "サイレン", "category": "機械・乗り物",
     "prompt": "an emergency vehicle siren wailing and approaching", "duration": 5.0},
    {"id": "helicopter", "label": "ヘリ", "category": "機械・乗り物",
     "prompt": "a helicopter rotor thumping as it flies overhead", "duration": 5.0},
    {"id": "robot", "label": "ロボット", "category": "機械・乗り物",
     "prompt": "a robotic servo whirring and clicking as it moves", "duration": 3.0},

    # ゲーム・バトル
    {"id": "click", "label": "クリック", "category": "ゲーム・バトル",
     "prompt": "a short crisp UI button click", "duration": 1.0},
    {"id": "coin", "label": "コイン", "category": "ゲーム・バトル",
     "prompt": "a bright retro video game coin pickup jingle", "duration": 1.5},
    {"id": "level_up", "label": "レベルアップ", "category": "ゲーム・バトル",
     "prompt": "an upbeat retro video game level-up fanfare", "duration": 2.5},
    {"id": "laser", "label": "レーザー", "category": "ゲーム・バトル",
     "prompt": "a sci-fi laser gun blast with a sharp pitch sweep", "duration": 1.5},
    {"id": "explosion", "label": "爆発", "category": "ゲーム・バトル",
     "prompt": "a powerful explosion with deep rumbling debris", "duration": 4.0},
    {"id": "punch", "label": "パンチ", "category": "ゲーム・バトル",
     "prompt": "a heavy punch impact with a sharp thud", "duration": 1.5},
    {"id": "sword", "label": "剣", "category": "ゲーム・バトル",
     "prompt": "a metal sword slash whoosh with a ringing clang", "duration": 2.0},
    {"id": "magic", "label": "魔法", "category": "ゲーム・バトル",
     "prompt": "a shimmering magical spell cast with sparkling chimes", "duration": 3.0},
    {"id": "power_up", "label": "パワーアップ", "category": "ゲーム・バトル",
     "prompt": "an ascending power-up sound effect with a bright synth sweep", "duration": 2.0},
    {"id": "error_beep", "label": "エラー音", "category": "ゲーム・バトル",
     "prompt": "a short harsh digital error beep", "duration": 1.0},
]

PRESETS_BY_ID = {p["id"]: p for p in PRESETS}
